name: autothreader_bot
description: Discord bot for automatically creating threads
version: 0.1.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  logging: ^1.0.2
  nyxx: ^3.2.7

dev_dependencies:
  lints: ^1.0.0
